// <auto-generated />
using System;
using AdessoLeague.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdessoLeague.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeagueDbContext))]
    partial class LeagueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdessoLeague.Domain.Draws.Draw", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer")
                        .HasColumnName("group_count");

                    b.Property<int>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.HasKey("Id")
                        .HasName("pk_draws");

                    b.ToTable("draws", (string)null);
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.DrawGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("Id")
                        .HasName("pk_draw_groups");

                    b.HasIndex("DrawId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_draw_groups_draw_id_name");

                    b.ToTable("draw_groups", (string)null);
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.DrawGroupTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DrawGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_group_id");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_draw_group_teams");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_draw_group_teams_team_id");

                    b.HasIndex("DrawGroupId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_draw_group_teams_draw_group_id_team_id");

                    b.HasIndex("DrawId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_draw_group_teams_draw_id_team_id");

                    b.ToTable("draw_group_teams", (string)null);
                });

            modelBuilder.Entity("AdessoLeague.Domain.Leagues.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_name");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Almanya"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Fransa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Hollanda"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Portekiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "İtalya"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "İspanya"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Belçika"
                        });
                });

            modelBuilder.Entity("AdessoLeague.Domain.Leagues.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_teams_country_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Adesso İstanbul"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Adesso Ankara"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Adesso İzmir"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Adesso Antalya"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Adesso Berlin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Adesso Frankfurt"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Adesso Münih"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Adesso Dortmund"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Adesso Paris"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Adesso Marsilya"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Adesso Nice"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Adesso Lyon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Adesso Amsterdam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Adesso Rotterdam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Adesso Lahey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Adesso Eindhoven"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Adesso Lisbon"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Adesso Porto"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Adesso Braga"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Adesso Coimbra"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Adesso Roma"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Adesso Milano"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Adesso Venedik"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Adesso Napoli"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Adesso Sevilla"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Adesso Madrid"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Adesso Barselona"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Adesso Granada"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000001"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Adesso Brüksel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000002"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Adesso Brugge"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000003"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Adesso Gent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000004"),
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Adesso Anvers"
                        });
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.Draw", b =>
                {
                    b.OwnsOne("AdessoLeague.Domain.Draws.Draw.DrawnBy#AdessoLeague.Domain.ValueObjects.DrawnBy", "DrawnBy", b1 =>
                        {
                            b1.Property<Guid>("DrawId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("drawn_by_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("drawn_by_last_name");

                            b1.HasKey("DrawId");

                            b1.ToTable("draws", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DrawId")
                                .HasConstraintName("fk_draws_draws_id");
                        });

                    b.Navigation("DrawnBy")
                        .IsRequired();
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.DrawGroup", b =>
                {
                    b.HasOne("AdessoLeague.Domain.Draws.Draw", null)
                        .WithMany("Groups")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draw_groups_draws_draw_id");
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.DrawGroupTeam", b =>
                {
                    b.HasOne("AdessoLeague.Domain.Draws.DrawGroup", null)
                        .WithMany("Teams")
                        .HasForeignKey("DrawGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draw_group_teams_draw_groups_draw_group_id");

                    b.HasOne("AdessoLeague.Domain.Draws.Draw", null)
                        .WithMany()
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draw_group_teams_draws_draw_id");

                    b.HasOne("AdessoLeague.Domain.Leagues.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_draw_group_teams_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AdessoLeague.Domain.Leagues.Team", b =>
                {
                    b.HasOne("AdessoLeague.Domain.Leagues.Country", null)
                        .WithMany("Teams")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_countries_country_id");
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.Draw", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("AdessoLeague.Domain.Draws.DrawGroup", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AdessoLeague.Domain.Leagues.Country", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
